<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Jogo25D</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Scenes\Characters\**" />
    <Compile Remove="Scenes\Entities\**" />
    <Compile Remove="Scenes\Levels\**" />
    <EmbeddedResource Remove="Scenes\Characters\**" />
    <EmbeddedResource Remove="Scenes\Entities\**" />
    <EmbeddedResource Remove="Scenes\Levels\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\Fonts\Planes_ValMore.ttf" />
    <Content Include="Assets\Icons\Bows\icon_bow_1.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_10.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_11.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_12.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_13.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_14.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_15.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_16.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_17.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_18.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_19.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_2.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_20.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_21.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_22.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_23.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_24.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_25.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_26.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_27.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_28.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_29.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_3.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_30.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_31.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_32.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_33.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_34.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_35.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_36.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_37.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_38.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_39.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_4.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_40.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_41.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_42.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_43.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_44.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_45.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_46.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_47.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_48.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_49.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_5.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_50.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_51.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_52.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_53.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_54.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_55.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_56.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_57.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_58.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_59.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_6.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_60.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_61.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_62.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_63.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_64.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_65.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_66.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_67.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_68.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_69.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_7.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_70.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_71.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_72.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_73.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_74.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_75.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_76.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_77.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_78.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_8.png" />
    <Content Include="Assets\Icons\Bows\icon_bow_9.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_1.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_10.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_11.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_12.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_13.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_14.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_15.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_16.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_17.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_18.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_19.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_2.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_20.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_21.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_22.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_23.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_24.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_25.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_26.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_27.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_28.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_29.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_3.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_30.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_31.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_32.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_33.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_34.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_35.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_36.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_37.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_38.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_39.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_4.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_40.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_5.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_6.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_7.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_8.png" />
    <Content Include="Assets\Icons\Effects\icon_effect_9.png" />
    <Content Include="Assets\Icons\Materials\icon_material_1.png" />
    <Content Include="Assets\Icons\Materials\icon_material_10.png" />
    <Content Include="Assets\Icons\Materials\icon_material_11.png" />
    <Content Include="Assets\Icons\Materials\icon_material_12.png" />
    <Content Include="Assets\Icons\Materials\icon_material_13.png" />
    <Content Include="Assets\Icons\Materials\icon_material_14.png" />
    <Content Include="Assets\Icons\Materials\icon_material_15.png" />
    <Content Include="Assets\Icons\Materials\icon_material_16.png" />
    <Content Include="Assets\Icons\Materials\icon_material_17.png" />
    <Content Include="Assets\Icons\Materials\icon_material_18.png" />
    <Content Include="Assets\Icons\Materials\icon_material_19.png" />
    <Content Include="Assets\Icons\Materials\icon_material_2.png" />
    <Content Include="Assets\Icons\Materials\icon_material_20.png" />
    <Content Include="Assets\Icons\Materials\icon_material_21.png" />
    <Content Include="Assets\Icons\Materials\icon_material_22.png" />
    <Content Include="Assets\Icons\Materials\icon_material_23.png" />
    <Content Include="Assets\Icons\Materials\icon_material_24.png" />
    <Content Include="Assets\Icons\Materials\icon_material_25.png" />
    <Content Include="Assets\Icons\Materials\icon_material_26.png" />
    <Content Include="Assets\Icons\Materials\icon_material_27.png" />
    <Content Include="Assets\Icons\Materials\icon_material_28.png" />
    <Content Include="Assets\Icons\Materials\icon_material_29.png" />
    <Content Include="Assets\Icons\Materials\icon_material_3.png" />
    <Content Include="Assets\Icons\Materials\icon_material_30.png" />
    <Content Include="Assets\Icons\Materials\icon_material_31.png" />
    <Content Include="Assets\Icons\Materials\icon_material_32.png" />
    <Content Include="Assets\Icons\Materials\icon_material_33.png" />
    <Content Include="Assets\Icons\Materials\icon_material_34.png" />
    <Content Include="Assets\Icons\Materials\icon_material_35.png" />
    <Content Include="Assets\Icons\Materials\icon_material_36.png" />
    <Content Include="Assets\Icons\Materials\icon_material_37.png" />
    <Content Include="Assets\Icons\Materials\icon_material_38.png" />
    <Content Include="Assets\Icons\Materials\icon_material_39.png" />
    <Content Include="Assets\Icons\Materials\icon_material_4.png" />
    <Content Include="Assets\Icons\Materials\icon_material_40.png" />
    <Content Include="Assets\Icons\Materials\icon_material_41.png" />
    <Content Include="Assets\Icons\Materials\icon_material_42.png" />
    <Content Include="Assets\Icons\Materials\icon_material_43.png" />
    <Content Include="Assets\Icons\Materials\icon_material_44.png" />
    <Content Include="Assets\Icons\Materials\icon_material_45.png" />
    <Content Include="Assets\Icons\Materials\icon_material_46.png" />
    <Content Include="Assets\Icons\Materials\icon_material_47.png" />
    <Content Include="Assets\Icons\Materials\icon_material_48.png" />
    <Content Include="Assets\Icons\Materials\icon_material_5.png" />
    <Content Include="Assets\Icons\Materials\icon_material_6.png" />
    <Content Include="Assets\Icons\Materials\icon_material_7.png" />
    <Content Include="Assets\Icons\Materials\icon_material_8.png" />
    <Content Include="Assets\Icons\Materials\icon_material_9.png" />
    <Content Include="Assets\Icons\Pickaxes\icon_pickaxe_1.png" />
    <Content Include="Assets\Icons\Pickaxes\icon_pickaxe_2.png" />
    <Content Include="Assets\Icons\Pickaxes\icon_pickaxe_3.png" />
    <Content Include="Assets\Icons\Pickaxes\icon_pickaxe_4.png" />
    <Content Include="Assets\Icons\Pickaxes\icon_pickaxe_5.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_1.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_10.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_11.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_12.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_13.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_14.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_15.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_16.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_17.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_18.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_19.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_2.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_20.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_21.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_22.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_23.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_24.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_25.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_26.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_27.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_28.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_29.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_3.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_30.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_31.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_32.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_33.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_34.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_35.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_36.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_37.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_38.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_39.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_4.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_40.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_41.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_42.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_43.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_44.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_45.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_46.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_47.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_48.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_5.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_6.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_7.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_8.png" />
    <Content Include="Assets\Icons\Potions\icon_potion_9.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_1.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_10.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_2.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_3.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_4.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_5.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_6.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_7.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_8.png" />
    <Content Include="Assets\Icons\Spells\icon_spell_9.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_1.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_10.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_11.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_12.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_13.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_14.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_15.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_16.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_17.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_18.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_19.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_2.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_20.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_21.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_22.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_23.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_24.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_25.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_26.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_27.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_28.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_29.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_3.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_30.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_31.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_32.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_33.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_34.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_35.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_36.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_37.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_38.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_39.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_4.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_40.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_41.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_42.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_43.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_44.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_45.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_46.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_47.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_48.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_49.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_5.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_50.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_51.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_52.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_53.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_54.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_55.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_56.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_57.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_58.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_59.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_6.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_60.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_61.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_62.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_63.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_64.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_65.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_66.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_67.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_68.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_69.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_7.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_70.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_8.png" />
    <Content Include="Assets\Icons\Swords\icon_sword_9.png" />
    <Content Include="Assets\Sprites\Character\charater.png" />
    <Content Include="Assets\Sprites\Slashs\1732c2d3-f548-4112-93ff-83b5f8dc3269.png" />
    <Content Include="Assets\Sprites\Slashs\17a1d930-e6cb-4c5a-b276-3ca0db25a05e.png" />
    <Content Include="Assets\Sprites\Slashs\18ab619e-1e36-4a80-962e-8199539de0e9.png" />
    <Content Include="Assets\Sprites\Slashs\2f2a083e-af1a-48f1-8d73-0aaffb11c33e.png" />
    <Content Include="Assets\Sprites\Slashs\32a600b0-45e3-4e04-96c1-5d7d92454f05.png" />
    <Content Include="Assets\Sprites\Slashs\39cf9aa1-2380-49af-aaa1-a8197b7ed795.png" />
    <Content Include="Assets\Sprites\Slashs\60b32f80-099b-421f-bd62-4bccbeb68bbe.png" />
    <Content Include="Assets\Sprites\Slashs\6532bf85-6258-4601-b060-b756c54d0030.png" />
    <Content Include="Assets\Sprites\Slashs\6c7ecfb5-e144-4f43-95fa-00db5b5ac3ed.png" />
    <Content Include="Assets\Sprites\Slashs\8228e81f-a58e-424f-89df-144f0ff10127.png" />
    <Content Include="Assets\Sprites\Slashs\840ba19a-8e17-4cd5-871d-f56977631e3d.png" />
    <Content Include="Assets\Sprites\Slashs\9ccf3905-a3bc-4c20-9f62-54091f914647.png" />
    <Content Include="Assets\Sprites\Slashs\b5770102-67c8-405e-8987-13880d79a70d.png" />
    <Content Include="Assets\Sprites\Slashs\f14c423e-85ea-4d6e-acd4-8765f7a6c5c9.png" />
    <Content Include="Assets\Sprites\Slashs\f785488d-fc2d-483c-a9cd-a3b31492c4b6.png" />
    <Content Include="Assets\Sprites\Speels\1.png" />
    <Content Include="Assets\Sprites\Speels\10.png" />
    <Content Include="Assets\Sprites\Speels\1_2.png" />
    <Content Include="Assets\Sprites\Speels\2.png" />
    <Content Include="Assets\Sprites\Speels\3.png" />
    <Content Include="Assets\Sprites\Speels\3_2.png" />
    <Content Include="Assets\Sprites\Speels\4.png" />
    <Content Include="Assets\Sprites\Speels\4_1.png" />
    <Content Include="Assets\Sprites\Speels\4_2.png" />
    <Content Include="Assets\Sprites\Speels\5.png" />
    <Content Include="Assets\Sprites\Speels\6.png" />
    <Content Include="Assets\Sprites\Speels\6_2.png" />
    <Content Include="Assets\Sprites\Speels\7.png" />
    <Content Include="Assets\Sprites\Speels\8.png" />
    <Content Include="Assets\Sprites\Speels\9.png" />
    <Content Include="Assets\Textures\1.png" />
    <Content Include="Assets\Textures\2.png" />
    <Content Include="Assets\Textures\3.png" />
    <Content Include="Assets\Textures\4.png" />
    <Content Include="Assets\Textures\5.png" />
    <Content Include="Assets\Textures\6.png" />
    <Content Include="Assets\Textures\Screenshot 2026-02-21 014440.png" />
    <Content Include="Assets\Textures\Screenshot 2026-02-21 014543.png" />
    <Content Include="Assets\Textures\Untitled.png" />
    <Content Include="Assets\Tiles\TX Chest Animation.png" />
    <Content Include="Assets\Tiles\TX FX Flame.png" />
    <Content Include="Assets\Tiles\TX FX Torch Flame.png" />
    <Content Include="Assets\Tiles\TX Tileset Ground.png" />
    <Content Include="Assets\Tiles\TX Village Props.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Assets\Audio\Music\.gitkeep" />
    <None Include="Assets\Audio\SFX\.gitkeep" />
    <None Include="Assets\Fonts\Planes_ValMore.ttf.import" />
    <None Include="Assets\Icons\Bows\icon_bow_1.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_10.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_11.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_12.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_13.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_14.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_15.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_16.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_17.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_18.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_19.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_2.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_20.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_21.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_22.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_23.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_24.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_25.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_26.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_27.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_28.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_29.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_3.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_30.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_31.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_32.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_33.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_34.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_35.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_36.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_37.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_38.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_39.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_4.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_40.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_41.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_42.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_43.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_44.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_45.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_46.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_47.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_48.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_49.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_5.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_50.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_51.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_52.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_53.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_54.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_55.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_56.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_57.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_58.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_59.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_6.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_60.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_61.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_62.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_63.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_64.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_65.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_66.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_67.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_68.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_69.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_7.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_70.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_71.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_72.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_73.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_74.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_75.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_76.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_77.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_78.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_8.png.import" />
    <None Include="Assets\Icons\Bows\icon_bow_9.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_1.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_10.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_11.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_12.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_13.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_14.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_15.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_16.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_17.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_18.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_19.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_2.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_20.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_21.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_22.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_23.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_24.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_25.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_26.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_27.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_28.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_29.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_3.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_30.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_31.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_32.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_33.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_34.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_35.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_36.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_37.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_38.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_39.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_4.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_40.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_5.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_6.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_7.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_8.png.import" />
    <None Include="Assets\Icons\Effects\icon_effect_9.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_1.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_10.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_11.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_12.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_13.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_14.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_15.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_16.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_17.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_18.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_19.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_2.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_20.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_21.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_22.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_23.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_24.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_25.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_26.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_27.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_28.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_29.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_3.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_30.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_31.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_32.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_33.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_34.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_35.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_36.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_37.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_38.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_39.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_4.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_40.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_41.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_42.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_43.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_44.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_45.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_46.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_47.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_48.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_5.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_6.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_7.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_8.png.import" />
    <None Include="Assets\Icons\Materials\icon_material_9.png.import" />
    <None Include="Assets\Icons\Pickaxes\icon_pickaxe_1.png.import" />
    <None Include="Assets\Icons\Pickaxes\icon_pickaxe_2.png.import" />
    <None Include="Assets\Icons\Pickaxes\icon_pickaxe_3.png.import" />
    <None Include="Assets\Icons\Pickaxes\icon_pickaxe_4.png.import" />
    <None Include="Assets\Icons\Pickaxes\icon_pickaxe_5.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_1.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_10.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_11.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_12.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_13.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_14.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_15.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_16.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_17.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_18.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_19.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_2.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_20.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_21.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_22.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_23.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_24.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_25.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_26.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_27.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_28.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_29.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_3.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_30.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_31.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_32.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_33.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_34.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_35.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_36.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_37.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_38.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_39.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_4.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_40.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_41.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_42.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_43.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_44.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_45.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_46.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_47.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_48.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_5.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_6.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_7.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_8.png.import" />
    <None Include="Assets\Icons\Potions\icon_potion_9.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_1.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_10.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_2.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_3.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_4.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_5.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_6.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_7.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_8.png.import" />
    <None Include="Assets\Icons\Spells\icon_spell_9.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_1.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_10.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_11.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_12.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_13.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_14.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_15.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_16.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_17.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_18.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_19.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_2.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_20.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_21.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_22.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_23.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_24.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_25.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_26.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_27.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_28.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_29.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_3.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_30.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_31.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_32.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_33.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_34.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_35.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_36.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_37.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_38.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_39.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_4.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_40.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_41.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_42.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_43.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_44.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_45.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_46.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_47.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_48.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_49.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_5.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_50.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_51.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_52.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_53.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_54.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_55.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_56.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_57.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_58.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_59.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_6.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_60.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_61.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_62.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_63.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_64.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_65.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_66.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_67.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_68.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_69.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_7.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_70.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_8.png.import" />
    <None Include="Assets\Icons\Swords\icon_sword_9.png.import" />
    <None Include="Assets\Sprites\.gitkeep" />
    <None Include="Assets\Sprites\Character\charater.png.import" />
    <None Include="Assets\Sprites\Slashs\1732c2d3-f548-4112-93ff-83b5f8dc3269.png.import" />
    <None Include="Assets\Sprites\Slashs\17a1d930-e6cb-4c5a-b276-3ca0db25a05e.png.import" />
    <None Include="Assets\Sprites\Slashs\18ab619e-1e36-4a80-962e-8199539de0e9.png.import" />
    <None Include="Assets\Sprites\Slashs\2f2a083e-af1a-48f1-8d73-0aaffb11c33e.png.import" />
    <None Include="Assets\Sprites\Slashs\32a600b0-45e3-4e04-96c1-5d7d92454f05.png.import" />
    <None Include="Assets\Sprites\Slashs\39cf9aa1-2380-49af-aaa1-a8197b7ed795.png.import" />
    <None Include="Assets\Sprites\Slashs\60b32f80-099b-421f-bd62-4bccbeb68bbe.png.import" />
    <None Include="Assets\Sprites\Slashs\6532bf85-6258-4601-b060-b756c54d0030.png.import" />
    <None Include="Assets\Sprites\Slashs\6c7ecfb5-e144-4f43-95fa-00db5b5ac3ed.png.import" />
    <None Include="Assets\Sprites\Slashs\8228e81f-a58e-424f-89df-144f0ff10127.png.import" />
    <None Include="Assets\Sprites\Slashs\840ba19a-8e17-4cd5-871d-f56977631e3d.png.import" />
    <None Include="Assets\Sprites\Slashs\9ccf3905-a3bc-4c20-9f62-54091f914647.png.import" />
    <None Include="Assets\Sprites\Slashs\b5770102-67c8-405e-8987-13880d79a70d.png.import" />
    <None Include="Assets\Sprites\Slashs\f14c423e-85ea-4d6e-acd4-8765f7a6c5c9.png.import" />
    <None Include="Assets\Sprites\Slashs\f785488d-fc2d-483c-a9cd-a3b31492c4b6.png.import" />
    <None Include="Assets\Sprites\Speels\1.png.import" />
    <None Include="Assets\Sprites\Speels\10.png.import" />
    <None Include="Assets\Sprites\Speels\1_2.png.import" />
    <None Include="Assets\Sprites\Speels\2.png.import" />
    <None Include="Assets\Sprites\Speels\3.png.import" />
    <None Include="Assets\Sprites\Speels\3_2.png.import" />
    <None Include="Assets\Sprites\Speels\4.png.import" />
    <None Include="Assets\Sprites\Speels\4_1.png.import" />
    <None Include="Assets\Sprites\Speels\4_2.png.import" />
    <None Include="Assets\Sprites\Speels\5.png.import" />
    <None Include="Assets\Sprites\Speels\6.png.import" />
    <None Include="Assets\Sprites\Speels\6_2.png.import" />
    <None Include="Assets\Sprites\Speels\7.png.import" />
    <None Include="Assets\Sprites\Speels\8.png.import" />
    <None Include="Assets\Sprites\Speels\9.png.import" />
    <None Include="Assets\Textures\.gitkeep" />
    <None Include="Assets\Textures\1.png.import" />
    <None Include="Assets\Textures\2.png.import" />
    <None Include="Assets\Textures\3.png.import" />
    <None Include="Assets\Textures\4.png.import" />
    <None Include="Assets\Textures\5.png.import" />
    <None Include="Assets\Textures\6.png.import" />
    <None Include="Assets\Textures\Screenshot 2026-02-21 014440.png.import" />
    <None Include="Assets\Textures\Screenshot 2026-02-21 014543.png.import" />
    <None Include="Assets\Textures\Untitled.png.import" />
    <None Include="Assets\Tiles\TX Chest Animation.png.import" />
    <None Include="Assets\Tiles\TX FX Flame.png.import" />
    <None Include="Assets\Tiles\TX FX Torch Flame.png.import" />
    <None Include="Assets\Tiles\TX Tileset Ground.png.import" />
    <None Include="Assets\Tiles\TX Village Props.png.import" />
    <None Include="DefaultTheme.tres" />
    <None Include="project.godot" />
    <None Include="Scenes\Main.tscn" />
    <None Include="Scenes\Managers\Managers.tscn" />
    <None Include="Scenes\UI\Console\Console.tscn" />
    <None Include="Scenes\UI\Hud\Hud.tscn" />
    <None Include="Scenes\UI\Inventory\Inventory.tscn" />
    <None Include="Scenes\UI\Pause\Pause.tscn" />
    <None Include="Scenes\UI\Ui.tscn" />
    <None Include="Scenes\World\Characters\Player.tscn" />
    <None Include="Scenes\World\Levels\Overworld.tscn" />
    <None Include="Scenes\World\Levels\Procedural.tscn" />
    <None Include="Scenes\World\Levels\Upsidedown.tscn" />
    <None Include="Scenes\World\Projectiles\Fireball.tscn" />
    <None Include="Scenes\World\Projectiles\GroundStrike.tscn" />
    <None Include="Scenes\World\Projectiles\Projectile.tscn" />
    <None Include="Scenes\World\Projectiles\Sword.tscn" />
    <None Include="Scenes\World\World.tscn" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Word\Actions\Resources\" />
  </ItemGroup>
</Project>