<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Jogo25D</RootNamespace>
    <DebugType>none</DebugType>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Scenes\Characters\**" />
    <Compile Remove="Scenes\Entities\**" />
    <Compile Remove="Scenes\Levels\**" />
    <EmbeddedResource Remove="Scenes\Characters\**" />
    <EmbeddedResource Remove="Scenes\Entities\**" />
    <EmbeddedResource Remove="Scenes\Levels\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\Fonts\Planes_ValMore.ttf" />
    <Content Include="Assets\Icons\Bows\Icon1.png" />
    <Content Include="Assets\Icons\Bows\Icon10.png" />
    <Content Include="Assets\Icons\Bows\Icon11.png" />
    <Content Include="Assets\Icons\Bows\Icon12.png" />
    <Content Include="Assets\Icons\Bows\Icon12_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon13.png" />
    <Content Include="Assets\Icons\Bows\Icon13_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon14.png" />
    <Content Include="Assets\Icons\Bows\Icon14_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon15.png" />
    <Content Include="Assets\Icons\Bows\Icon15_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon16.png" />
    <Content Include="Assets\Icons\Bows\Icon16_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon17.png" />
    <Content Include="Assets\Icons\Bows\Icon18.png" />
    <Content Include="Assets\Icons\Bows\Icon19.png" />
    <Content Include="Assets\Icons\Bows\Icon19_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon1_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon2.png" />
    <Content Include="Assets\Icons\Bows\Icon20.png" />
    <Content Include="Assets\Icons\Bows\Icon20_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon21.png" />
    <Content Include="Assets\Icons\Bows\Icon21_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon22.png" />
    <Content Include="Assets\Icons\Bows\Icon22_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon23.png" />
    <Content Include="Assets\Icons\Bows\Icon23_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon24.png" />
    <Content Include="Assets\Icons\Bows\Icon25.png" />
    <Content Include="Assets\Icons\Bows\Icon25_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon26.png" />
    <Content Include="Assets\Icons\Bows\Icon26_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon27.png" />
    <Content Include="Assets\Icons\Bows\Icon27_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon28.png" />
    <Content Include="Assets\Icons\Bows\Icon29.png" />
    <Content Include="Assets\Icons\Bows\Icon29_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon2_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon3.png" />
    <Content Include="Assets\Icons\Bows\Icon30.png" />
    <Content Include="Assets\Icons\Bows\Icon30_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon31.png" />
    <Content Include="Assets\Icons\Bows\Icon32.png" />
    <Content Include="Assets\Icons\Bows\Icon32_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon33.png" />
    <Content Include="Assets\Icons\Bows\Icon34.png" />
    <Content Include="Assets\Icons\Bows\Icon35.png" />
    <Content Include="Assets\Icons\Bows\Icon36.png" />
    <Content Include="Assets\Icons\Bows\Icon37.png" />
    <Content Include="Assets\Icons\Bows\Icon37_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon38.png" />
    <Content Include="Assets\Icons\Bows\Icon38_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon39.png" />
    <Content Include="Assets\Icons\Bows\Icon3_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon4.png" />
    <Content Include="Assets\Icons\Bows\Icon40.png" />
    <Content Include="Assets\Icons\Bows\Icon40_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon41.png" />
    <Content Include="Assets\Icons\Bows\Icon42.png" />
    <Content Include="Assets\Icons\Bows\Icon43.png" />
    <Content Include="Assets\Icons\Bows\Icon43_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon44.png" />
    <Content Include="Assets\Icons\Bows\Icon44_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon45.png" />
    <Content Include="Assets\Icons\Bows\Icon45_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon46.png" />
    <Content Include="Assets\Icons\Bows\Icon46_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon47.png" />
    <Content Include="Assets\Icons\Bows\Icon47_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon48.png" />
    <Content Include="Assets\Icons\Bows\Icon4_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon5.png" />
    <Content Include="Assets\Icons\Bows\Icon6.png" />
    <Content Include="Assets\Icons\Bows\Icon6_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon7.png" />
    <Content Include="Assets\Icons\Bows\Icon8.png" />
    <Content Include="Assets\Icons\Bows\Icon8_no_effect.png" />
    <Content Include="Assets\Icons\Bows\Icon9.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_01.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_02.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_03.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_04.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_05.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_06.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_07.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_08.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_09.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_10.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_11.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_12.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_13.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_14.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_15.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_16.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_17.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_18.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_19.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_20.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_21.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_22.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_23.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_24.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_25.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_26.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_27.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_28.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_29.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_30.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_31.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_32.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_33.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_34.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_35.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_36.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_37.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_38.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_39.png" />
    <Content Include="Assets\Icons\Effects\Skillicon14_40.png" />
    <Content Include="Assets\Icons\Materials\Icon1.png" />
    <Content Include="Assets\Icons\Materials\Icon10.png" />
    <Content Include="Assets\Icons\Materials\Icon11.png" />
    <Content Include="Assets\Icons\Materials\Icon12.png" />
    <Content Include="Assets\Icons\Materials\Icon13.png" />
    <Content Include="Assets\Icons\Materials\Icon14.png" />
    <Content Include="Assets\Icons\Materials\Icon15.png" />
    <Content Include="Assets\Icons\Materials\Icon16.png" />
    <Content Include="Assets\Icons\Materials\Icon17.png" />
    <Content Include="Assets\Icons\Materials\Icon18.png" />
    <Content Include="Assets\Icons\Materials\Icon19.png" />
    <Content Include="Assets\Icons\Materials\Icon2.png" />
    <Content Include="Assets\Icons\Materials\Icon20.png" />
    <Content Include="Assets\Icons\Materials\Icon21.png" />
    <Content Include="Assets\Icons\Materials\Icon22.png" />
    <Content Include="Assets\Icons\Materials\Icon23.png" />
    <Content Include="Assets\Icons\Materials\Icon24.png" />
    <Content Include="Assets\Icons\Materials\Icon25.png" />
    <Content Include="Assets\Icons\Materials\Icon26.png" />
    <Content Include="Assets\Icons\Materials\Icon27.png" />
    <Content Include="Assets\Icons\Materials\Icon28.png" />
    <Content Include="Assets\Icons\Materials\Icon29.png" />
    <Content Include="Assets\Icons\Materials\Icon3.png" />
    <Content Include="Assets\Icons\Materials\Icon30.png" />
    <Content Include="Assets\Icons\Materials\Icon31.png" />
    <Content Include="Assets\Icons\Materials\Icon32.png" />
    <Content Include="Assets\Icons\Materials\Icon33.png" />
    <Content Include="Assets\Icons\Materials\Icon34.png" />
    <Content Include="Assets\Icons\Materials\Icon35.png" />
    <Content Include="Assets\Icons\Materials\Icon36.png" />
    <Content Include="Assets\Icons\Materials\Icon37.png" />
    <Content Include="Assets\Icons\Materials\Icon38.png" />
    <Content Include="Assets\Icons\Materials\Icon39.png" />
    <Content Include="Assets\Icons\Materials\Icon4.png" />
    <Content Include="Assets\Icons\Materials\Icon40.png" />
    <Content Include="Assets\Icons\Materials\Icon41.png" />
    <Content Include="Assets\Icons\Materials\Icon42.png" />
    <Content Include="Assets\Icons\Materials\Icon43.png" />
    <Content Include="Assets\Icons\Materials\Icon44.png" />
    <Content Include="Assets\Icons\Materials\Icon45.png" />
    <Content Include="Assets\Icons\Materials\Icon46.png" />
    <Content Include="Assets\Icons\Materials\Icon47.png" />
    <Content Include="Assets\Icons\Materials\Icon48.png" />
    <Content Include="Assets\Icons\Materials\Icon5.png" />
    <Content Include="Assets\Icons\Materials\Icon6.png" />
    <Content Include="Assets\Icons\Materials\Icon7.png" />
    <Content Include="Assets\Icons\Materials\Icon8.png" />
    <Content Include="Assets\Icons\Materials\Icon9.png" />
    <Content Include="Assets\Icons\Pickaxes\sPickaxe1.png" />
    <Content Include="Assets\Icons\Pickaxes\sPickaxe2.png" />
    <Content Include="Assets\Icons\Pickaxes\sPickaxe3.png" />
    <Content Include="Assets\Icons\Pickaxes\sPickaxe4.png" />
    <Content Include="Assets\Icons\Pickaxes\sPickaxe5.png" />
    <Content Include="Assets\Icons\Potions\Icon1.png" />
    <Content Include="Assets\Icons\Potions\Icon10.png" />
    <Content Include="Assets\Icons\Potions\Icon11.png" />
    <Content Include="Assets\Icons\Potions\Icon12.png" />
    <Content Include="Assets\Icons\Potions\Icon13.png" />
    <Content Include="Assets\Icons\Potions\Icon14.png" />
    <Content Include="Assets\Icons\Potions\Icon15.png" />
    <Content Include="Assets\Icons\Potions\Icon16.png" />
    <Content Include="Assets\Icons\Potions\Icon17.png" />
    <Content Include="Assets\Icons\Potions\Icon18.png" />
    <Content Include="Assets\Icons\Potions\Icon19.png" />
    <Content Include="Assets\Icons\Potions\Icon2.png" />
    <Content Include="Assets\Icons\Potions\Icon20.png" />
    <Content Include="Assets\Icons\Potions\Icon21.png" />
    <Content Include="Assets\Icons\Potions\Icon22.png" />
    <Content Include="Assets\Icons\Potions\Icon23.png" />
    <Content Include="Assets\Icons\Potions\Icon24.png" />
    <Content Include="Assets\Icons\Potions\Icon25.png" />
    <Content Include="Assets\Icons\Potions\Icon26.png" />
    <Content Include="Assets\Icons\Potions\Icon27.png" />
    <Content Include="Assets\Icons\Potions\Icon28.png" />
    <Content Include="Assets\Icons\Potions\Icon29.png" />
    <Content Include="Assets\Icons\Potions\Icon3.png" />
    <Content Include="Assets\Icons\Potions\Icon30.png" />
    <Content Include="Assets\Icons\Potions\Icon31.png" />
    <Content Include="Assets\Icons\Potions\Icon32.png" />
    <Content Include="Assets\Icons\Potions\Icon33.png" />
    <Content Include="Assets\Icons\Potions\Icon34.png" />
    <Content Include="Assets\Icons\Potions\Icon35.png" />
    <Content Include="Assets\Icons\Potions\Icon36.png" />
    <Content Include="Assets\Icons\Potions\Icon37.png" />
    <Content Include="Assets\Icons\Potions\Icon38.png" />
    <Content Include="Assets\Icons\Potions\Icon39.png" />
    <Content Include="Assets\Icons\Potions\Icon4.png" />
    <Content Include="Assets\Icons\Potions\Icon40.png" />
    <Content Include="Assets\Icons\Potions\Icon41.png" />
    <Content Include="Assets\Icons\Potions\Icon42.png" />
    <Content Include="Assets\Icons\Potions\Icon43.png" />
    <Content Include="Assets\Icons\Potions\Icon44.png" />
    <Content Include="Assets\Icons\Potions\Icon45.png" />
    <Content Include="Assets\Icons\Potions\Icon46.png" />
    <Content Include="Assets\Icons\Potions\Icon47.png" />
    <Content Include="Assets\Icons\Potions\Icon48.png" />
    <Content Include="Assets\Icons\Potions\Icon5.png" />
    <Content Include="Assets\Icons\Potions\Icon6.png" />
    <Content Include="Assets\Icons\Potions\Icon7.png" />
    <Content Include="Assets\Icons\Potions\Icon8.png" />
    <Content Include="Assets\Icons\Potions\Icon9.png" />
    <Content Include="Assets\Icons\Spells\Icon_01.png" />
    <Content Include="Assets\Icons\Spells\Icon_02.png" />
    <Content Include="Assets\Icons\Spells\Icon_03.png" />
    <Content Include="Assets\Icons\Spells\Icon_04.png" />
    <Content Include="Assets\Icons\Spells\Icon_05.png" />
    <Content Include="Assets\Icons\Spells\Icon_06.png" />
    <Content Include="Assets\Icons\Spells\Icon_07.png" />
    <Content Include="Assets\Icons\Spells\Icon_08.png" />
    <Content Include="Assets\Icons\Spells\Icon_09.png" />
    <Content Include="Assets\Icons\Spells\Icon_10.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_01.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_02.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_03.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_04.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_05.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_06.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_07.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_08.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_09.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_10.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_11.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_12.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_13.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_14.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_15.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_16.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_17.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_18.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_19.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_20.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_21.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_22.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_23.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_24.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_25.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_26.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_27.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_28.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_29.png" />
    <Content Include="Assets\Icons\Swords\icon_32_2_30.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_01.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_02.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_03.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_04.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_05.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_06.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_07.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_08.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_09.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_10.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_11.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_12.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_13.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_14.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_15.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_16.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_17.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_18.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_19.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_20.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_21.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_22.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_23.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_24.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_25.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_26.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_27.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_28.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_29.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_30.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_31.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_32.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_33.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_34.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_35.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_36.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_37.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_38.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_39.png" />
    <Content Include="Assets\Icons\Swords\Iicon_32_40.png" />
    <Content Include="Assets\Sprites\Speels\1.png" />
    <Content Include="Assets\Sprites\Speels\10.png" />
    <Content Include="Assets\Sprites\Speels\1_2.png" />
    <Content Include="Assets\Sprites\Speels\2.png" />
    <Content Include="Assets\Sprites\Speels\3.png" />
    <Content Include="Assets\Sprites\Speels\3_2.png" />
    <Content Include="Assets\Sprites\Speels\4.png" />
    <Content Include="Assets\Sprites\Speels\4_1.png" />
    <Content Include="Assets\Sprites\Speels\4_2.png" />
    <Content Include="Assets\Sprites\Speels\5.png" />
    <Content Include="Assets\Sprites\Speels\6.png" />
    <Content Include="Assets\Sprites\Speels\6_2.png" />
    <Content Include="Assets\Sprites\Speels\7.png" />
    <Content Include="Assets\Sprites\Speels\8.png" />
    <Content Include="Assets\Sprites\Speels\9.png" />
    <Content Include="Assets\Textures\Screenshot 2026-02-21 014440.png" />
    <Content Include="Assets\Textures\Screenshot 2026-02-21 014543.png" />
    <Content Include="Assets\Textures\Untitled.png" />
    <Content Include="Assets\Tiles\TX Chest Animation.png" />
    <Content Include="Assets\Tiles\TX FX Flame.png" />
    <Content Include="Assets\Tiles\TX FX Torch Flame.png" />
    <Content Include="Assets\Tiles\TX Tileset Ground.png" />
    <Content Include="Assets\Tiles\TX Village Props.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".gitignore" />
    <None Include="Assets\Audio\Music\.gitkeep" />
    <None Include="Assets\Audio\SFX\.gitkeep" />
    <None Include="Assets\Fonts\.gitkeep" />
    <None Include="Assets\Sprites\.gitkeep" />
    <None Include="Assets\Textures\.gitkeep" />
    <None Include="Assets\Textures\Screenshot 2026-02-21 014440.png.import" />
    <None Include="Assets\Textures\Screenshot 2026-02-21 014543.png.import" />
    <None Include="configure.ps1" />
    <None Include="DefaultTheme.tres" />
    <None Include="format.ps1" />
    <None Include="Jogo25D.sln" />
    <None Include="project.godot" />
    <None Include="README.md" />
    <None Include="Scenes\Main.tscn" />
    <None Include="Scenes\Managers\Managers.tscn" />
    <None Include="Scenes\UI\Console\Console.tscn" />
    <None Include="Scenes\UI\Hud\Hud.tscn" />
    <None Include="Scenes\UI\Inventory\Inventory.tscn" />
    <None Include="Scenes\UI\Pause\Pause.tscn" />
    <None Include="Scenes\UI\Ui.tscn" />
    <None Include="Scenes\World\Characters\Player.tscn" />
    <None Include="Scenes\World\Levels\Overword.tscn" />
    <None Include="Scenes\World\Levels\Procedural.tscn" />
    <None Include="Scenes\World\Levels\Upsidedown.tscn" />
    <None Include="Scenes\World\Projectiles\Fireball.tscn" />
    <None Include="Scenes\World\Projectiles\GroundStrike.tscn" />
    <None Include="Scenes\World\Projectiles\Projectile.tscn" />
    <None Include="Scenes\World\Projectiles\Sword.tscn" />
    <None Include="Scenes\World\World.tscn" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Logs\" />
  </ItemGroup>
</Project>